# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Product(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, product_id: str=None, name: str=None, active: bool=True, company_id: str=None):  # noqa: E501
        """Product - a model defined in Swagger

        :param product_id: The product_id of this Product.  # noqa: E501
        :type product_id: str
        :param name: The name of this Product.  # noqa: E501
        :type name: str
        :param active: The active of this Product.  # noqa: E501
        :type active: bool
        :param company_id: The company_id of this Product.  # noqa: E501
        :type company_id: str
        """
        self.swagger_types = {
            'product_id': str,
            'name': str,
            'active': bool,
            'company_id': str
        }

        self.attribute_map = {
            'product_id': 'product_id',
            'name': 'name',
            'active': 'active',
            'company_id': 'company_id'
        }
        self._product_id = product_id
        self._name = name
        self._active = active
        self._company_id = company_id

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_id(self) -> str:
        """Gets the product_id of this Product.

        Auto-generated primary key field  # noqa: E501

        :return: The product_id of this Product.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """Sets the product_id of this Product.

        Auto-generated primary key field  # noqa: E501

        :param product_id: The product_id of this Product.
        :type product_id: str
        """
        if product_id is None:
            raise ValueError("Invalid value for `product_id`, must not be `None`")  # noqa: E501

        self._product_id = product_id

    @property
    def name(self) -> str:
        """Gets the name of this Product.


        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product.


        :param name: The name of this Product.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def active(self) -> bool:
        """Gets the active of this Product.


        :return: The active of this Product.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Product.


        :param active: The active of this Product.
        :type active: bool
        """

        self._active = active

    @property
    def company_id(self) -> str:
        """Gets the company_id of this Product.

        This property is a reference to a Company  # noqa: E501

        :return: The company_id of this Product.
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id: str):
        """Sets the company_id of this Product.

        This property is a reference to a Company  # noqa: E501

        :param company_id: The company_id of this Product.
        :type company_id: str
        """
        if company_id is None:
            raise ValueError("Invalid value for `company_id`, must not be `None`")  # noqa: E501

        self._company_id = company_id
