# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Task(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, task_id: str=None, name: str=None, active: bool=True, stage_id: str=None):  # noqa: E501
        """Task - a model defined in Swagger

        :param task_id: The task_id of this Task.  # noqa: E501
        :type task_id: str
        :param name: The name of this Task.  # noqa: E501
        :type name: str
        :param active: The active of this Task.  # noqa: E501
        :type active: bool
        :param stage_id: The stage_id of this Task.  # noqa: E501
        :type stage_id: str
        """
        self.swagger_types = {
            'task_id': str,
            'name': str,
            'active': bool,
            'stage_id': str
        }

        self.attribute_map = {
            'task_id': 'task_id',
            'name': 'name',
            'active': 'active',
            'stage_id': 'stage_id'
        }
        self._task_id = task_id
        self._name = name
        self._active = active
        self._stage_id = stage_id

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def task_id(self) -> str:
        """Gets the task_id of this Task.

        Auto-generated primary key field  # noqa: E501

        :return: The task_id of this Task.
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id: str):
        """Sets the task_id of this Task.

        Auto-generated primary key field  # noqa: E501

        :param task_id: The task_id of this Task.
        :type task_id: str
        """
        if task_id is None:
            raise ValueError("Invalid value for `task_id`, must not be `None`")  # noqa: E501

        self._task_id = task_id

    @property
    def name(self) -> str:
        """Gets the name of this Task.


        :return: The name of this Task.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Task.


        :param name: The name of this Task.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def active(self) -> bool:
        """Gets the active of this Task.


        :return: The active of this Task.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Task.


        :param active: The active of this Task.
        :type active: bool
        """

        self._active = active

    @property
    def stage_id(self) -> str:
        """Gets the stage_id of this Task.

        This property is a reference to a Stage  # noqa: E501

        :return: The stage_id of this Task.
        :rtype: str
        """
        return self._stage_id

    @stage_id.setter
    def stage_id(self, stage_id: str):
        """Sets the stage_id of this Task.

        This property is a reference to a Stage  # noqa: E501

        :param stage_id: The stage_id of this Task.
        :type stage_id: str
        """
        if stage_id is None:
            raise ValueError("Invalid value for `stage_id`, must not be `None`")  # noqa: E501

        self._stage_id = stage_id
